<div id="loading-wrapper" class="loading-wrapper" >
    <div class="loadingio-spinner-ball-a1x5ajkgc7d" ><div class="ldio-agl3gtzdkf">
        <div></div>
    </div></div>
</div>
<style type="text/css">
    @keyframes ldio-agl3gtzdkf {
        0%, 100% {
            animation-timing-function: cubic-bezier(0.45,0,0.9,0.55)
        }
        0% {
            transform: translate(0,0)
        }
        50% {
            transform: translate(0,108px);
            animation-timing-function: cubic-bezier(0,0.45,0.55,0.9);
        }
        100% {
            transform: translate(0,0);
        }
    }
        .loading-wrapper{
            background-color: rgba(0,0,0,0.5);
            z-index: 999;
            width: 100%;
            height: 100%;
            position: fixed;
            display: flex;
            align-items: center;
            justify-content: center;
        }
    .ldio-agl3gtzdkf div {
        position: absolute;
        width: 52px;
        height: 52px;
        border-radius: 50%;
        background: #006637;
        left: 74px;
        top: 20px;
        animation: ldio-agl3gtzdkf 1s linear infinite;
    }
    .loadingio-spinner-ball-a1x5ajkgc7d {
        width: 200px;
        height: 200px;
        display: inline-block;
        overflow: hidden;

    }
    .ldio-agl3gtzdkf {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(1);
        backface-visibility: hidden;
        transform-origin: 0 0; /* see note above */
    }
    .ldio-agl3gtzdkf div { box-sizing: content-box; }
    /* generated by https://loading.io/ */
</style>






